FROM node:alpine
WORKDIR /app

COPY ./package.json .

RUN npm install
COPY . .

# CMD ["npm", "run", "test", "--", "--watchAll=false"]  # USE THIS FOR TEST CASES IN DEV MODE.
CMD ["npm", "run", "start"]