version: '3'
services: 
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
    backend:
        build: 
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes:
            - /app/node_modules
    frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules