FROM node:alpine
WORKDIR /app

# Copy package.json into workdir
COPY ./package.json .

RUN npm install

# Copy remaining files
COPY . .

# Default command of this image
# CMD ["npm", "run", "test"] # USE THIS ONLY FOR RUNNING TESTS
CMD ["npm", "run", "start"] 